BEGIN TRANSACTION;
INSERT INTO Accounts VALUES 
(105,'Arun',2000);
SAVE TRANSACTION SavePoint1;
INSERT INTO Accounts VALUES 
(106,'Kiran',3000);
ROLLBACK TRANSACTION SavePoint1;
COMMIT;

CREATE TABLE Accounts
(
AccountID INT PRIMARY KEY,
CustomerName VARCHAR(50),
Balance MONEY
);